//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string MembershipId { get; set; }
        public string ProfilePicUrl { get; set; }
        public string FileUrl { get; set; }
        public string MembershipType { get; set; }
        public System.DateTime Date { get; set; }
        public string ShowOnHomePage { get; set; }
    }
}
